# See https://docs.codecov.com/docs/commit-status
coverage:
  status:
    # The whole project must reach a coverage of 80% for the `codecov/project`
    # check to succeed.
    project:
      default:
        target: 80%
        threshold: 5% # How much the coverage can decrease.
        paths:
          - "src"
          # advanced settings
        branches:
          - main
        informational: false
        only_pulls: false
